### Get all documents for a project
GET http://localhost:5000/api/documents/6888cd3b07b4af54e301ef72
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjg4OGMxNTUwNWRmMDU5MDQ0NGY3ZTMxIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTc1Mzc5NDc2MCwiZXhwIjoxNzUzNzk4MzYwfQ.moikvBzYzoWqPD3XtzmX2LpN8JMYDXiJ-tRE8ZtBvgE
